name: test
on:
  push:
    branches:
      - master
jobs:
  run-script:
    name: Run test script to change path
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change environment
        run: sudo -E ./change_github_path.sh
      - name: Check path changed
        run: ./check_github_path.sh
